### ISSUE TITLE
IntelliJ IDEA 2017 support

### ISSUE THREAD

**Issue by joseph-montanez** [neochief/squirrel-lang-idea-plugin#1]
I am trying to recompile the plugin to debug why I am unable to setup the SDK, it seems to fail to detect the version using this pattern `"#define SQUIRREL_VERSION[\t ]+_SC\\(\"Squirrel ([0-9\\.]*?) stable\"\\)"`. No matter what I put into the SDK setup it fails to detect the version. So I started to setup IDEA for plugin development and struggling to get the plugin to compile. Here are some things that are happening:

1.  jFlex 1.4 does not have --charat command line option. If I remove that the files are generated but then there are issues with some switch / if statements. This might have to do with the skeleton file used but I have no idea what skeleton file I should be using. So I started jumping back versions I've found on the IDEA Community repo. Overall I am struggling with even downloading the freaking repo as it just stalls out. I found a skeleton file that works better but still has `Error:(434, 32) java: array required, but java.lang.CharSequence found` basically `zzBufferL[zzCurrentPosL++];` should be `zzBufferL.charAt(zzCurrentPosL++);`. That makes the --charat command line option fall into place. I am able to compile but the charAt issue will keep coming back if I want to make changes to the flex files...

2. I tried switching to jFlex 1.6.1 same --charat issue, but also this line does not compile:
    `ANY=[ \t\f\r\na-zA-Z0-9_\-\.,+-*&\^%@!~|<>/\?:;\(\)\{\}\[\]]`
    It looks like that line is not used anyways so if I comment it out, I get the following errors:
    - `Error:(428, 45) java: incompatible types: java.lang.CharSequence cannot be converted to char[]` (This seems to be an issue with the skeleton?)
    - `Error:(881, 55) java: cannot find symbol
       symbol:   variable zzCMapL
       location: class com.sqide.lexer._SquirrelLexer`

Here is the skeleton file I am using: https://github.com/JetBrains/intellij-community/blob/master/tools/lexer/idea-flex.skeleton

Once I was able to recompile the plugin, the version detection seems to work just fine. There is a null reference error that I would like to fix. Overall I want to be able to build the project without manually adjusting the java files generated from the .flex files.

So I think the best question to ask is what version of the SDK did you use?

**Comment by neochief** [comment]
Hey Joseph,

I'm sorry, but I don't remember the version. It was really long time ago when I worked on this project for the last time. Let me try to setup everything once again, maybe I'll be able to make it work.

**Comment by neochief** [comment]
Okay, I was able to build it. There was a bug in that ANY line, the extra - after + sign, which didn't cause problems before, but apparently doesn't work with flex 1.7. I've fixed that and also updated the build script to work with modern flex version supplied with recent sources of IDEA.

Please, pull the updates to the plugin on your end.
- Make sure that IDEA sources are placed on the same directory level as the plugin's folder and called "idea" in order for a build script to work.
- Also make sure that you checkout a proper tag in your IDEA sources that matches your installed IDEA version. Given that you installed the latest version of IDEA community edition, that should do it "git checkout --tag idea/172.3317"
- Given that your IDEA has a bash script plugin installed, building the plugin requires running the proper build configuration (Build lexer and parser). After that, run another build configuration called "Plugin" to make sure it launches in IDE. It did work for me, at least.

By the way, after building the plugin, I downloaded the 3.1 Squirrel build from the official website and the plugin was able to detect and add it as proper Squirrel SDK.

Please let me know if you still having issues launching the beast. I know how frustrating it might feel, I felt the same way when I wrote the plugin initially.
